import Head from "next/head"
import { useEffect } from "react"
import Button from "components/Button"
import GitHub from "components/Icons/GitHub"
import { loginWithGitHub } from "@/firebase/client"
import styles from "styles/index.module.css"
import { useRouter } from "next/router"
import useUser, { USER_STATES } from "hooks/useUser"

export default function Index() {
  const user = useUser()
  const router = useRouter()

  useEffect(() => {
    user && router.replace("/home")
  }, [user])

  const handleClick = () => {
    loginWithGitHub()
  }

  return (
    <>
      <Head>
        <title>Devtter</title>
        <meta name="description" content="Generated by josé" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.section}>
        <img className={styles.logo} src="/logo.png" alt="logo" />
        <h1 className={styles.title}>Devtter</h1>
        <h2 className={styles.subtitle}>
          Talk about development with developers
        </h2>
        <div className={styles.button}>
          {user === USER_STATES.NOT_LOGGED && (
            <Button onClick={handleClick}>
              <GitHub fill="#fff" />
              Login with GitHub
            </Button>
          )}
          {user === USER_STATES.NOT_KNOW && (
            <img src="/loading.gif" width={25} height={25} />
          )}
        </div>
      </section>
    </>
  )
}
